export const iconsList = {
  'clear sky': 'https://openweathermap.org/img/wn/01d.png',
  'few clouds': 'https://openweathermap.org/img/wn/02d.png',
  'scattered clouds': 'https://openweathermap.org/img/wn/03d.png',
  'broken clouds': 'https://openweathermap.org/img/wn/04d.png',
  'shower rain': 'https://openweathermap.org/img/wn/09d.png',
  rain: 'https://openweathermap.org/img/wn/10d.png',
  thunderstorm: 'https://openweathermap.org/img/wn/11d.png',
  snow: 'https://openweathermap.org/img/wn/13d.png',
  mist: 'https://openweathermap.org/img/wn/50d.png',
  smoke: 'https://openweathermap.org/img/wn/50d.png',
  haze: 'https://openweathermap.org/img/wn/50d.png',
  dust: 'https://openweathermap.org/img/wn/50d.png',
  fog: 'https://openweathermap.org/img/wn/50d.png',
  sand: 'https://openweathermap.org/img/wn/50d.png',
  'volcanic ash': 'https://openweathermap.org/img/wn/50d.png',
  squalls: 'https://openweathermap.org/img/wn/50d.png',
  tornado: 'https://openweathermap.org/img/wn/50d.png',
};
